In [2]:
# Import NumPy
import numpy as np


In [5]:
# 1D Array (Vector)
arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [6]:
# Basic Math (Where NumPy Shines)

print(arr + 5)
print(arr * 2)

[15 25 35 45]
[20 40 60 80]


In [7]:
# Mean, Sum (Used Everywhere in ML)

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

Sum: 100
Mean: 25.0


In [8]:
# 2D Array (Matrix – CORE FOR AI)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)
print("Shape:", matrix.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [9]:
print(matrix[0, 0])
print(matrix[1, 2])

1
6


In [ ]:
# Real AI-Style Example

marks = np.array([70, 85, 90, 60, 75])

average = np.mean(marks)
passed = marks >= 70

print("Average: ", average)
print("Passed students :", passed)

Average:  76.0
Passed students : [ True  True  True False  True]


In [ ]:
# VERY IMPORTANT CONCEPT (Read Slowly)
# # Dictionary vs NumPy (Simple Rule)

# Dictionary → labels, meaning, metadata
student = {"name": "Amit", "marks": 85}

# NumPy array → pure numbers for computation
marks = np.array([85, 78, 90])

# AI models do NOT care about names, only numbers.